### ISSUE TITLE
Handling failure

### ISSUE THREAD

**Issue by cworsley4** [JMPerez/passport-spotify#10]
I'm sure I'm missing something obvious, but, is there a hook to where we can handle oAuth failures? By that I mean, if the authorization code is invalid, can we specify a flash message? If the user doesn't authorize us to access the account can we detect that and respond accordingly?

**Comment by JMPerez** [comment]
Did you check [Passport's documentation on authentication](http://passportjs.org/docs#authenticate) I believe this is something that is handled by Passport, and the strategy only returns the error if any.

**Comment by JMPerez** [comment]
Closing the ticket for inactivity. Feel free to reopen it.
