### ISSUE TITLE
Greenkeeper integration

### ISSUE THREAD

**Issue by hughrawlinson** [JMPerez/passport-spotify#12]
Hey, it looks like you don't have [greenkeeper](https://greenkeeper.io/) set up on this repo. Worth doing to make sure you support latest versions of express 😄

**Comment by JMPerez** [comment]
@hughrawlinson I hadn't tried Greenkeeper before. I have just integrated it, so I'll keep an eye on PRs with updates for the dependencies.

**Comment by JMPerez** [comment]
Fixed through https://github.com/JMPerez/passport-spotify/pull/13

**Comment by hughrawlinson** [comment]
Thanks @JMPerez! :)
