### ISSUE TITLE
Spotify Login - Dialog to Switch Accounts isn't showing up

### ISSUE THREAD

**Issue by scotty914** [JMPerez/passport-spotify#3]
I'm making the following function call to authenticate the user and the dialog to switch Spotify accounts doesn't show up. I'm supporting sessions using 
require('express-session'), 
app.use(session({ secret: 'keyboard cat' })); 
app.use(passport.session()); 

and I log the user out with this function call

app.get('/logout', function(req, res){
  req.session.destroy(function (err) {
    res.redirect('/'); //Inside a callback… bulletproof!
  });
});

Here is my request to authenticate the user, where I want the dialog to switch accounts to show up, but it doesn't.

app.get('/auth/spotify',
  passport.authenticate('spotify', {scope: ['user-read-email', 'user-read-private', 'user-read-private', 'playlist-read', 'playlist-read-private']}),
  function(req, res){
});

passport.use(new SpotifyStrategy({
  clientID: appKey,
  clientSecret: appSecret,
  show_dialog: true,
  callbackURL: 'http://localhost:3000/callback',
  },
  function(accessToken, refreshToken, profile, done) {
    access = accessToken;
    var bad = {
      "accessToken": accessToken,
      "refreshToken": refreshToken,
      "profile": profile
    };
    process.nextTick(function () {
      return done(null, profile);
    });
}));

**Comment by scotty914** [comment]
I noticed that it does work whenever I close the browser, meaning I was using cookie sessions and those were preventing the login dialog from appearing.

**Comment by JMPerez** [comment]
@scotty914 Even though you solved it, it's true that at the moment there is no way to set the `show_dialog` parameter in the SpotifyStrategy. I'm reopening this issue to address it.
