### ISSUE TITLE
Where is the accesstoken stored?

### ISSUE THREAD

**Issue by jamesla** [JMPerez/passport-spotify#4]
How can I access the accesstoken once logged in? I can't seem to find it.

**Comment by JMPerez** [comment]
Have a look at [the example provided with the code](https://github.com/JMPerez/passport-spotify/blob/master/examples/login/app.js#L40). The callback receives the access token, that you can then persist if you want to. [Internally](https://github.com/JMPerez/passport-spotify/blob/master/lib/passport-spotify/strategy.js#L128), the access token is used to fetch the user's profile from Spotify.

For more information about OAuth 2.0 in PassportJS, please check the [OAuth guide (section OAuth 2.0)](http://passportjs.org/guide/oauth/) on Passport's website.
