### ISSUE TITLE
Session: false

### ISSUE THREAD

**Issue by fgerschau** [JMPerez/passport-spotify#60]
Hi,
I want to use this library for my API and I don't want to register a passport session. Is there a way to do that already? If not I'd be ready to work on that.

**Comment by JMPerez** [comment]
No idea if that’s possible to be honest. Feel free to contribute and link
to some documentation for that feature in passport.

**Comment by fgerschau** [comment]
Just wanted to update this thread, seems like oAuth requires sessions in order to work. [See this issue of the twitter strategy](https://github.com/jaredhanson/passport-twitter/issues/43).

**Comment by JMPerez** [comment]
Does that mean we can close the ticket since this can’t be implemented?
