### ISSUE TITLE
using this with ios sdk

### ISSUE THREAD

**Issue by twilly86** [JMPerez/passport-spotify#8]
How would I use passport spotify with the ios sdk?  I'd like to get a refresh token stored in my database that I can then use in the background.  I'm able to authenticate and get an authorization code back from the ios sdk.  How do I use passport to exchange that for a refresh token?

**Comment by JMPerez** [comment]
Passport abstracts you from the internals of the authorization code flow, and it's ideal for implementing the whole thing for a website. In your case, if you are already able to get a code back, you might want to use something simple like based on [the Web API auth examples](https://github.com/spotify/web-api-auth-examples/blob/master/authorization_code/app.js#L58).

**Comment by neildevas** [comment]
@twilly86 did you end up implementing the Auth flow yourself? I have the same issue as you, but I want to keep the functionality of passport sessions too.
