### ISSUE TITLE
Access to expires_in

### ISSUE THREAD

**Issue by bencmbrook** [JMPerez/passport-spotify#9]
Is 3600 a safe assumption for expires_in? If not, can it be made available in the verify callback?

**Comment by JMPerez** [comment]
@bencmbrook 3600 is the current value, but that doesn't mean that Spotify can't change their mind at some point.

I can't find any passport strategy where they are exposing this, nor any mention [in the docs](http://passportjs.org/docs/oauth) on how to expose it properly.

Best way is to just suppose that if you get a 401, you need to refresh the access token. Note that even if you store it for one hour, a user might still revoke permissions for your app or Spotify might revoke issued access tokens, in which case your token will throw a 401 code.

I'm closing this ticket for the time being. If you find an example of a strategy using it, let me know.
