### ISSUE TITLE
Spotify API not return email when register/login via spotify

### ISSUE THREAD

**Issue by lyudad** [JMPerez/passport-spotify#93]
I'm not sure does it issue with spotify or with passport.
Problem is that profile not always return email

const spotifyCallbackMiddleware = passport.authenticate('spotify', {
failureRedirect: ${CALLBACK_URL}/auth/login,
});

```
passport.use(
 new SpotifyStrategy(
  {
    clientID,
    clientSecret,
     callbackURL
},
    function(accessToken, refreshToken, expires_in, profile, done) {
     return done(null, { accessToken, refreshToken, expires_in, profile });
     }
));

```
expect that profile include email. For most users it work, but some have empty email

**Comment by afeld** [comment]
Perhaps some of their authorizations were missing the `user-read-email` [scope](https://developer.spotify.com/documentation/general/guides/scopes/)?

**Comment by JMPerez** [comment]
@lyudad, as @afeld says, you need to ask for that scope to get user's email back.
